# Generated by Django 4.0.5 on 2022-06-29 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_alter_studentmodel_grades_alter_studentmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='average_grade',
        ),
    ]
