# Generated by Django 4.0.5 on 2022-06-29 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0003_remove_studentmodel_average_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='average_grade',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
